excel_upload/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace="myapp")),
]

myapp/urls.py
from django.urls import path

from . import views

from .views import search

app_name = "myapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', search,name="search"),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
import openpyxl
from django.http import HttpResponse
from django.views.generic import ListView

def index(request):
    if "GET" == request.method:
        return render(request, 'myapp/index.html', {})
    else:
        excel_file = request.FILES["excel_file"]

        # you may put validations here to check extension or file size

        wb = openpyxl.load_workbook(excel_file)

        # getting all sheets
        sheets = wb.sheetnames
        #print(sheets)

        # getting a particular sheet
        worksheet = wb[sheets[0]]
        #print(worksheet)


        # getting active sheet
        #active_sheet = wb.active
        #print(active_sheet)

        # reading a cell
        #print(worksheet["A1"].value)

        excel_data = list()
        # iterating over the rows and
        # getting value from each cell in row
        for row in worksheet.iter_rows():
            row_data = list()
            temp = 0
            for cell in row:
                
                value = ""
                if cell.value is not None:
                    value = str(cell.value)
                    if temp == 2:
                      value = value + 'second' 
                      ### CHECK VALUE INSIDE DATABASE ####################
                      # if in database:
                      
                      # temp test REPLACE LATER WITH 'IF IN DATABASE:'
                      if "鋼" in value:
                          value = value + '!'
                temp += 1
                row_data.append(value)
                #print(cell.value)
            excel_data.append(row_data)
        headers = list()
        for i in range(3):
            headers.append(excel_data.pop(0))
        return render(request, 'myapp/index.html', {"excel_data":excel_data, "headers":headers})


def search(request):
    if "GET" == request.method:
        return render(request, 'myapp/results.html', {})
    else:
        result_list = list()
           
        form = request.POST
        #print(form['results_btn'])
        
        keyword_str = form['results_btn']
        print(keyword_str)

        #test!!!!!!!!!!!!
        result_list.append('apple')
        result_list.append('book')
        result_list.append('choo choo train')
        result_list.append(keyword_str)


        return render(request, 'myapp/results.html', {"result_list":result_list})

 

myapp/templates/myapp/index.html
<html lang="ja">
    <head>
        <title>
            エクセル　アップロード
        </title>
    <style> 
        table, td, th{
            border: 1px solid black;
            border-collapse: collapse;
            font-size: 80%;
        }
        tr:nth-of-type(even) {
            background-color: #96D4D4;
        }
        tr:nth-of-type(odd) {
            background-color: solid white;
        }
        tr:hover {
            background-color: #7FFF00;
        }

        .button {
          background-color: #555555;
          border: none;
          color: white;
          border: 2px #555555;
          padding: 4px 8px;
          text-align: center;
          transition-duration: 0.4s;
          text-decoration: none;
          display: inline-block;
          font-size: 12px;
          font-weight: bold;
          margin: 4px 2px;
          transition-duration: 0.4s;
        }
      
        .button:hover {
          background-color: white;
          color: #555555;
        }

        .disabled {
          opacity: 0.3;
          pointer-events: none;
        }

        .cursor-disable {
          cursor: not-allowed;
        }

        .submit-btn {
          border: 1px solid black; 
          background-color: #1E90FF; 
          padding:5px; 
          color: white;
          border-radius: 2px; 
          cursor: pointer;
        }

    </style>
    </head>

    <body lang="ja" style="margin-top: 30px;margin-left: 30px;">
        <h1>エクセル　アップロード</h1>
        <form action="{% url "myapp:index" %}" lang="ja" method="post" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="アップロード"
                   class="submit-btn">
        </form>

        <p></p>
        <hr>

        <table>
            <thead>
            {% for hd in headers %}
                <tr>
                    {% for cell in hd %}
                        {% if 'second' in cell %}
                            <th>{{cell|cut:"second"}}</th>
                        {% elif '!' in cell %}
                            <th>{{cell|cut:"!"}}</th>
                        {% else %}
                            <th>{{cell}}</th>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </thead>

            <tbody>
                {% for row in excel_data %}
                    <tr>
                        {% for cell in row %}
                            {% if 'second' in cell %}
                                <td>
                                    <!-- <a href="/search" target="_blank">{{ cell|cut:"!" }}</a> -->
                                    {% if '!' in cell %}
                                        {{cell|cut:"second!"}}
                                        <form action="{% url 'myapp:search' %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" 
                                                style="cursor: pointer;"
                                                name='results_btn' 
                                                class="button"
                                                value="{{cell|cut:"second!"}}">検索結果</button>
                                        </form>
                                    {% else %}
                                        {{cell|cut:"second"}}
                                        <form class="cursor-disable">
                                        <button class="button disabled">検索結果</button>
                                        </form> 
                                    {% endif %}
                                </td>
                            {% else %}
                                <td>{{cell}}</td>
                            {% endif %} 
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>
</html>

myapp/templates/myapp/results.html
<html>
    <head>
        <title>
            Search Results
        </title>
    </head>

    <body>
        <h1>Search Results</h1>
        <ul>
            {% for res in result_list %}
                <li>{{ res }}</li>
            {% endfor %}
    </body>
</html>